// swiftlint:disable file_length
import Foundation

// MARK: - WordList
// possibleAnswers  – 2 315 words from Josh Wardle's original Wordle answer list
//                    (gist.github.com/cfreshman/a03ef2cba789d8cf00c08f767e0fad7b)
// additionalGuesses – common 5-letter words accepted as guesses but never answers
//                    (includes the popular opener ADIEU and other Wordle-valid words)
// allowedWords     – union of both, used for guess validation
// answers / allWords – backward-compat aliases so WordleGame.swift needs no changes

enum WordList {

    // MARK: - Possible daily answer words
    static let possibleAnswers: [String] = [
        // A
        "aback","abase","abate","abbey","abbot","abhor","abide","abled","abode","abort",
        "about","above","abuse","abyss","acorn","acrid","actor","acute","adage","adapt",
        "adept","admin","admit","adobe","adopt","adore","adorn","adult","affix","afire",
        "afoot","afoul","after","again","agape","agate","agent","agile","aging","aglow",
        "agony","agora","agree","ahead","aider","aisle","alarm","album","alert","algae",
        "alibi","alien","align","alike","alive","allay","alley","allot","allow","alloy",
        "aloft","alone","along","aloof","aloud","alpha","altar","alter","amass","amaze",
        "amber","amble","amend","amiss","amity","among","ample","amply","amuse","angel",
        "anger","angle","angry","angst","anime","ankle","annex","annoy","annul","anode",
        "antic","anvil","aorta","apart","aphid","aping","apnea","apple","apply","apron",
        "aptly","arbor","ardor","arena","argue","arise","armor","aroma","arose","array",
        "arrow","arson","artsy","ascot","ashen","aside","askew","assay","asset","atoll",
        "atone","attic","audio","audit","augur","aunty","avail","avert","avian","avoid",
        "await","awake","award","aware","awash","awful","awoke","axial","axiom","axion",
        "azure",
        // B
        "bacon","badge","badly","bagel","baggy","baker","baler","balmy","banal","banjo",
        "barge","baron","basal","basic","basil","basin","basis","baste","batch","bathe",
        "baton","batty","bawdy","bayou","beach","beady","beard","beast","beech","beefy",
        "befit","began","begat","beget","begin","begun","being","belch","belie","belle",
        "belly","below","bench","beret","berry","berth","beset","betel","bevel","bezel",
        "bible","bicep","biddy","bigot","bilge","billy","binge","bingo","biome","birch",
        "birth","bison","bitty","black","blade","blame","bland","blank","blare","blast",
        "blaze","bleak","bleat","bleed","bleep","blend","bless","blimp","blind","blink",
        "bliss","blitz","bloat","block","bloke","blond","blood","bloom","blown","bluer",
        "bluff","blunt","blurb","blurt","blush","board","boast","bobby","boney","bongo",
        "bonus","booby","boost","booth","booty","booze","boozy","borax","borne","bosom",
        "bossy","botch","bough","boule","bound","bowel","boxer","brace","braid","brain",
        "brake","brand","brash","brass","brave","bravo","brawl","brawn","bread","break",
        "breed","briar","bribe","brick","bride","brief","brine","bring","brink","briny",
        "brisk","broad","broil","broke","brood","brook","broom","broth","brown","brunt",
        "brush","brute","buddy","budge","buggy","bugle","build","built","bulge","bulky",
        "bully","bunch","bunny","burly","burnt","burst","bused","bushy","butch","butte",
        "buxom","buyer","bylaw",
        // C
        "cabal","cabby","cabin","cable","cacao","cache","cacti","caddy","cadet","cagey",
        "cairn","camel","cameo","canal","candy","canny","canoe","canon","caper","caput",
        "carat","cargo","carol","carry","carve","caste","catch","cater","catty","caulk",
        "cause","cavil","cease","cedar","cello","chafe","chaff","chain","chair","chalk",
        "champ","chant","chaos","chard","charm","chart","chase","chasm","cheap","cheat",
        "check","cheek","cheer","chess","chest","chick","chide","chief","child","chili",
        "chill","chime","china","chirp","chock","choir","choke","chord","chore","chose",
        "chuck","chump","chunk","churn","chute","cider","cigar","cinch","circa","civic",
        "civil","clack","claim","clamp","clang","clank","clash","clasp","class","clean",
        "clear","cleat","cleft","clerk","click","cliff","climb","cling","clink","cloak",
        "clock","clone","close","cloth","cloud","clout","clove","clown","cluck","clued",
        "clump","clung","coach","coast","cobra","cocoa","colon","color","comet","comfy",
        "comic","comma","conch","condo","conic","copse","coral","corer","corny","couch",
        "cough","could","count","coupe","court","coven","cover","covet","covey","cower",
        "coyly","crack","craft","cramp","crane","crank","crash","crass","crate","crave",
        "crawl","craze","crazy","creak","cream","credo","creed","creek","creep","creme",
        "crepe","crept","cress","crest","crick","cried","crier","crime","crimp","crisp",
        "croak","crock","crone","crony","crook","cross","croup","crowd","crown","crude",
        "cruel","crumb","crump","crush","crust","crypt","cubic","cumin","curio","curly",
        "curry","curse","curve","curvy","cutie","cyber","cycle","cynic",
        // D
        "daddy","daily","dairy","daisy","dally","dance","dandy","datum","daunt","dealt",
        "death","debar","debit","debug","debut","decal","decay","decor","decoy","decry",
        "defer","deign","deity","delay","delta","delve","demon","demur","denim","dense",
        "depot","depth","derby","deter","detox","deuce","devil","diary","dicey","digit",
        "dilly","dimly","diner","dingo","dingy","diode","dirge","dirty","disco","ditch",
        "ditto","ditty","diver","dizzy","dodge","dodgy","dogma","doing","dolly","donor",
        "donut","dopey","doubt","dough","dowdy","dowel","downy","dowry","dozen","draft",
        "drain","drake","drama","drank","drape","drawl","drawn","dread","dream","dress",
        "dried","drier","drift","drill","drink","drive","droit","droll","drone","drool",
        "droop","dross","drove","drown","druid","drunk","dryer","dryly","duchy","dully",
        "dummy","dumpy","dunce","dusky","dusty","dutch","duvet","dwarf","dwell","dwelt",
        "dying",
        // E
        "eager","eagle","early","earth","easel","eaten","eater","ebony","eclat","edict",
        "edify","eerie","egret","eight","eject","eking","elate","elbow","elder","elect",
        "elegy","elfin","elide","elite","elope","elude","email","embed","ember","emcee",
        "empty","enact","endow","enema","enemy","enjoy","ennui","ensue","enter","entry",
        "envoy","epoch","epoxy","equal","equip","erase","erect","erode","error","erupt",
        "essay","ester","ether","ethic","ethos","etude","evade","event","every","evict",
        "evoke","exact","exalt","excel","exert","exile","exist","expel","extol","extra",
        "exult","eying",
        // F
        "fable","facet","faint","fairy","faith","false","fancy","fanny","farce","fatal",
        "fatty","fault","fauna","favor","feast","fecal","feign","fella","felon","femme",
        "femur","fence","feral","ferry","fetal","fetch","fetid","fetus","fever","fewer",
        "fiber","fibre","ficus","field","fiend","fiery","fifth","fifty","fight","filer",
        "filet","filly","filmy","filth","final","finch","finer","first","fishy","fixer",
        "fizzy","fjord","flack","flail","flair","flake","flaky","flame","flank","flare",
        "flash","flask","fleck","fleet","flesh","flick","flier","fling","flint","flirt",
        "float","flock","flood","floor","flora","floss","flour","flout","flown","fluff",
        "fluid","fluke","flume","flung","flunk","flush","flute","flyer","foamy","focal",
        "focus","foggy","foist","folio","folly","foray","force","forge","forgo","forte",
        "forth","forty","forum","found","foyer","frail","frame","frank","fraud","freak",
        "freed","freer","fresh","friar","fried","frill","frisk","fritz","frock","frond",
        "front","frost","froth","frown","froze","fruit","fudge","fugue","fully","fungi",
        "funky","funny","furor","furry","fussy","fuzzy",
        // G
        "gaffe","gaily","gamer","gamma","gamut","gassy","gaudy","gauge","gaunt","gauze",
        "gavel","gawky","gayer","gayly","gazer","gecko","geeky","geese","genie","genre",
        "ghost","ghoul","giant","giddy","gipsy","girly","girth","given","giver","glade",
        "gland","glare","glass","glaze","gleam","glean","glide","glint","gloat","globe",
        "gloom","glory","gloss","glove","glyph","gnash","gnome","godly","going","golem",
        "golly","gonad","goner","goody","gooey","goofy","goose","gorge","gouge","gourd",
        "grace","grade","graft","grail","grain","grand","grant","grape","graph","grasp",
        "grass","grate","grave","gravy","graze","great","greed","green","greet","grief",
        "grill","grime","grimy","grind","gripe","groan","groin","groom","grope","gross",
        "group","grout","grove","growl","grown","gruel","gruff","grunt","guard","guava",
        "guess","guest","guide","guild","guile","guilt","guise","gulch","gully","gumbo",
        "gummy","guppy","gusto","gusty","gypsy",
        // H
        "habit","hairy","halve","handy","happy","hardy","harem","harpy","harry","harsh",
        "haste","hasty","hatch","hater","haunt","haute","haven","havoc","hazel","heady",
        "heard","heart","heath","heave","heavy","hedge","hefty","heist","helix","hello",
        "hence","heron","hilly","hinge","hippo","hippy","hitch","hoard","hobby","hoist",
        "holly","homer","honey","honor","horde","horny","horse","hotel","hotly","hound",
        "house","hovel","hover","howdy","human","humid","humor","humph","humus","hunch",
        "hunky","hurry","husky","hussy","hutch","hydro","hyena","hymen","hyper",
        // I
        "icily","icing","ideal","idiom","idiot","idler","idyll","igloo","iliac","image",
        "imbue","impel","imply","inane","inbox","incur","index","inept","inert","infer",
        "ingot","inlay","inlet","inner","input","inter","intro","ionic","irate","irony",
        "islet","issue","itchy","ivory",
        // J
        "jaunt","jazzy","jelly","jerky","jetty","jewel","jiffy","joint","joist","joker",
        "jolly","joust","judge","juice","juicy","jumbo","jumpy","junta","junto","juror",
        // K
        "kappa","karma","kayak","kebab","khaki","kinky","kiosk","kitty","knack","knave",
        "knead","kneed","kneel","knelt","knife","knock","knoll","known","koala","krill",
        // L
        "label","labor","laden","ladle","lager","lance","lanky","lapel","lapse","large",
        "larva","lasso","latch","later","lathe","latte","laugh","layer","leach","leafy",
        "leaky","leant","leapt","learn","lease","leash","least","leave","ledge","leech",
        "leery","lefty","legal","leggy","lemon","lemur","leper","level","lever","libel",
        "liege","light","liken","lilac","limbo","limit","linen","liner","lingo","lipid",
        "lithe","liver","livid","llama","loamy","loath","lobby","local","locus","lodge",
        "lofty","logic","login","loopy","loose","lorry","loser","louse","lousy","lover",
        "lower","lowly","loyal","lucid","lucky","lumen","lumpy","lunar","lunch","lunge",
        "lupus","lurch","lurid","lusty","lying","lymph","lynch","lyric",
        // M
        "macaw","macho","macro","madam","madly","mafia","magic","magma","maize","major",
        "maker","mambo","mamma","mammy","manga","mange","mango","mangy","mania","manic",
        "manly","manor","maple","march","marry","marsh","mason","masse","match","matey",
        "mauve","maxim","maybe","mayor","mealy","meant","meaty","mecca","medal","media",
        "medic","melee","melon","mercy","merge","merit","merry","metal","meter","metro",
        "micro","midge","midst","might","milky","mimic","mince","miner","minim","minor",
        "minty","minus","mirth","miser","missy","mocha","modal","model","modem","mogul",
        "moist","molar","moldy","money","month","moody","moose","moral","moron","morph",
        "mossy","motel","motif","motor","motto","moult","mound","mount","mourn","mouse",
        "mouth","mover","movie","mower","mucky","mucus","muddy","mulch","mummy","munch",
        "mural","murky","mushy","music","musky","musty","myrrh",
        // N
        "nadir","naive","nanny","nasal","nasty","natal","naval","navel","needy","neigh",
        "nerdy","nerve","never","newer","newly","nicer","niche","niece","night","ninja",
        "ninny","ninth","noble","nobly","noise","noisy","nomad","noose","north","nosey",
        "notch","novel","nudge","nurse","nutty","nylon","nymph",
        // O
        "oaken","obese","occur","ocean","octal","octet","odder","oddly","offal","offer",
        "often","olden","older","olive","ombre","omega","onion","onset","opera","opine",
        "opium","optic","orbit","order","organ","other","otter","ought","ounce","outdo",
        "outer","outgo","ovary","ovate","overt","ovine","ovoid","owing","owner","oxide",
        "ozone",
        // P
        "paddy","pagan","paint","paler","palsy","panel","panic","pansy","papal","paper",
        "parer","parka","parry","parse","party","pasta","paste","pasty","patch","patio",
        "patsy","patty","pause","payee","payer","peace","peach","pearl","pecan","pedal",
        "penal","pence","penne","penny","perch","peril","perky","pesky","pesto","petal",
        "petty","phase","phone","phony","photo","piano","picky","piece","piety","piggy",
        "pilot","pinch","piney","pinky","pinto","piper","pique","pitch","pithy","pivot",
        "pixel","pixie","pizza","place","plaid","plain","plait","plane","plank","plant",
        "plate","plaza","plead","pleat","plied","plier","pluck","plumb","plume","plump",
        "plunk","plush","poesy","point","poise","poker","polar","polka","polyp","pooch",
        "poppy","porch","poser","posit","posse","pouch","pound","pouty","power","prank",
        "prawn","preen","press","price","prick","pride","pried","prime","primo","print",
        "prior","prism","privy","prize","probe","prone","prong","proof","prose","proud",
        "prove","prowl","proxy","prude","prune","psalm","pubic","pudgy","puffy","pulpy",
        "pulse","punch","pupal","pupil","puppy","puree","purer","purge","purse","pushy",
        "putty","pygmy",
        // Q
        "quack","quail","quake","qualm","quark","quart","quash","quasi","queen","queer",
        "quell","query","quest","queue","quick","quiet","quill","quilt","quirk","quite",
        "quota","quote","quoth",
        // R
        "rabbi","rabid","racer","radar","radii","radio","rainy","raise","rajah","rally",
        "ralph","ramen","ranch","randy","range","rapid","rarer","raspy","ratio","ratty",
        "raven","rayon","razor","reach","react","ready","realm","rearm","rebar","rebel",
        "rebus","rebut","recap","recur","recut","reedy","refer","refit","regal","rehab",
        "reign","relax","relay","relic","remit","renal","renew","repay","repel","reply",
        "rerun","reset","resin","retch","retro","retry","reuse","revel","revue","rhino",
        "rhyme","rider","ridge","rifle","right","rigid","rigor","rinse","ripen","riper",
        "risen","riser","risky","rival","river","rivet","roach","roast","robin","robot",
        "rocky","rodeo","roger","rogue","roomy","roost","rotor","rouge","rough","round",
        "rouse","route","rover","rowdy","rower","royal","ruddy","ruder","rugby","ruler",
        "rumba","rumor","rupee","rural","rusty",
        // S
        "sadly","safer","saint","salad","sally","salon","salsa","salty","salve","salvo",
        "sandy","saner","sappy","sassy","satin","satyr","sauce","saucy","sauna","saute",
        "savor","savoy","savvy","scald","scale","scalp","scaly","scamp","scant","scare",
        "scarf","scary","scene","scent","scion","scoff","scold","scone","scoop","scope",
        "score","scorn","scour","scout","scowl","scram","scrap","scree","screw","scrub",
        "scrum","scuba","sedan","seedy","segue","seize","semen","sense","sepia","serif",
        "serum","serve","setup","seven","sever","sewer","shack","shade","shady","shaft",
        "shake","shaky","shale","shall","shalt","shame","shank","shape","shard","share",
        "shark","sharp","shave","shawl","shear","sheen","sheep","sheer","sheet","sheik",
        "shelf","shell","shied","shift","shine","shiny","shire","shirk","shirt","shoal",
        "shock","shone","shook","shoot","shore","shorn","short","shout","shove","shown",
        "showy","shrew","shrub","shrug","shuck","shunt","shush","shyly","siege","sieve",
        "sight","sigma","silky","silly","since","sinew","singe","siren","sissy","sixth",
        "sixty","skate","skier","skiff","skill","skimp","skirt","skulk","skull","skunk",
        "slack","slain","slang","slant","slash","slate","slave","sleek","sleep","sleet",
        "slept","slice","slick","slide","slime","slimy","sling","slink","sloop","slope",
        "slosh","sloth","slump","slung","slunk","slurp","slush","slyly","smack","small",
        "smart","smash","smear","smell","smelt","smile","smirk","smite","smith","smock",
        "smoke","smoky","smote","snack","snail","snake","snaky","snare","snarl","sneak",
        "sneer","snide","sniff","snipe","snoop","snore","snort","snout","snowy","snuck",
        "snuff","soapy","sober","soggy","solar","solid","solve","sonar","sonic","sooth",
        "sooty","sorry","sound","south","sower","space","spade","spank","spare","spark",
        "spasm","spawn","speak","spear","speck","speed","spell","spelt","spend","spent",
        "sperm","spice","spicy","spied","spiel","spike","spiky","spill","spilt","spine",
        "spiny","spire","spite","splat","split","spoil","spoke","spoof","spook","spool",
        "spoon","spore","sport","spout","spray","spree","sprig","spunk","spurn","spurt",
        "squad","squat","squib","stack","staff","stage","staid","stain","stair","stake",
        "stale","stalk","stall","stamp","stand","stank","stare","stark","start","stash",
        "state","stave","stead","steak","steal","steam","steed","steel","steep","steer",
        "stein","stern","stick","stiff","still","stilt","sting","stink","stint","stock",
        "stoic","stoke","stole","stomp","stone","stony","stood","stool","stoop","store",
        "stork","storm","story","stout","stove","strap","straw","stray","strip","strut",
        "stuck","study","stuff","stump","stung","stunk","stunt","style","suave","sugar",
        "suing","suite","sulky","sully","sumac","sunny","super","surer","surge","surly",
        "sushi","swami","swamp","swarm","swash","swath","swear","sweat","sweep","sweet",
        "swell","swept","swift","swill","swine","swing","swirl","swish","swoon","swoop",
        "sword","swore","sworn","swung","synod","syrup",
        // T
        "tabby","table","taboo","tacit","tacky","taffy","taint","taken","taker","tally",
        "talon","tamer","tango","tangy","taper","tapir","tardy","tarot","taste","tasty",
        "tatty","taunt","tawny","teach","teary","tease","teddy","teeth","tempo","tenet",
        "tenor","tense","tenth","tepee","tepid","terra","terse","testy","thank","theft",
        "their","theme","there","these","theta","thick","thief","thigh","thing","think",
        "third","thong","thorn","those","three","threw","throb","throw","thrum","thumb",
        "thump","thyme","tiara","tibia","tidal","tiger","tight","tilde","timer","timid",
        "tipsy","titan","tithe","title","toast","today","toddy","token","tonal","tonga",
        "tonic","tooth","topaz","topic","torch","torso","torus","total","totem","touch",
        "tough","towel","tower","toxic","toxin","trace","track","tract","trade","trail",
        "train","trait","tramp","trash","trawl","tread","treat","trend","triad","trial",
        "tribe","trice","trick","tried","tripe","trite","troll","troop","trope","trout",
        "trove","truce","truck","truer","truly","trump","trunk","truss","trust","truth",
        "tryst","tubal","tuber","tulip","tulle","tumor","tunic","turbo","tutor","twang",
        "tweak","tweed","tweet","twice","twine","twirl","twist","twixt","tying",
        // U
        "udder","ulcer","ultra","umbra","uncle","uncut","under","undid","undue","unfed",
        "unfit","unify","union","unite","unity","unlit","unmet","unset","untie","until",
        "unwed","unzip","upper","upset","urban","urine","usage","usher","using","usual",
        "usurp","utile","utter",
        // V
        "vague","valet","valid","valor","value","valve","vapid","vapor","vault","vaunt",
        "vegan","venom","venue","verge","verse","verso","verve","vicar","video","vigil",
        "vigor","villa","vinyl","viola","viper","viral","virus","visit","visor","vista",
        "vital","vivid","vixen","vocal","vodka","vogue","voice","voila","vomit","voter",
        "vouch","vowel","vying",
        // W
        "wacky","wafer","wager","wagon","waist","waive","waltz","warty","waste","watch",
        "water","waver","waxen","weary","weave","wedge","weedy","weigh","weird","welch",
        "welsh","wench","whack","whale","wharf","wheat","wheel","whelp","where","which",
        "whiff","while","whine","whiny","whirl","whisk","white","whole","whoop","whose",
        "widen","wider","widow","width","wield","wight","willy","wimpy","wince","winch",
        "windy","wiser","wispy","witch","witty","woken","woman","women","woody","wooer",
        "wooly","woozy","wordy","world","worry","worse","worst","worth","would","wound",
        "woven","wrack","wrath","wreak","wreck","wrest","wring","wrist","write","wrong",
        "wrote","wrung","wryly",
        // Y – Z
        "yacht","yearn","yeast","yield","young","youth",
        "zebra","zesty","zonal",
    ]

    // MARK: - Extra valid guesses (never chosen as answers, but accepted input)
    // Covers popular openers (adieu, ourie, reais …) and other Wordle-legal words.
    static let additionalGuesses: [String] = [
        "aahed","aalii","abaci","aback","abaft","abash","abaya","abhor","aboon","abris",
        "abysm","acerb","ached","ackee","acmes","acned","acnes","acock","acold","acred",
        "acted","actin","addax","adder","adeem","adieu","adman","admen","admix","adown",
        "adoze","adunc","aegis","aeons","afoul","agaze","agene","agist","agley","agmas",
        "agone","agons","agued","agues","aheap","ahull","aided","aioli","aired","airts",
        "aitch","ajiva","akela","akene","alane","alans","alarm","alder","aldol","aleph",
        "algid","algum","allod","almah","almeh","almes","alods","alowe","alume","alums",
        "amain","ambry","amice","amici","amide","amine","amino","amole","amort","amour",
        "ampul","ancon","anear","anele","anent","anile","anils","anise","ankus","annul",
        "anoas","anomy","ansae","antae","antas","antre","apian","apish","apnea","apode",
        "aport","apose","appel","arced","arhat","ariel","arils","armet","arnut","aroid",
        "arpen","arras","arris","arums","arval","arvos","aspic","assai","atilt","atman",
        "atoms","atone","atony","atopy","audad","aurae","aurar","aural","autre","auxin",
        "avian","avion","aviso","awash","awing","axile","axion","axiom","axite","axled",
        "azide","azine","azole","azote","azoth","babka","baccy","balky","balls","balmy",
        "baser","bated","bathe","batik","baulk","bayou","beamy","beefy","beget","begum",
        "being","belay","belie","betel","bhang","bicep","bight","bigly","biome","biped",
        "bitch","bitsy","blear","bleat","bleed","blini","bliss","bluer","bluet","bluey",
        "boast","boggy","bolar","bolus","bonce","boney","booby","boppy","borax","boric",
        "bossy","botch","bothy","bousy","bowie","boxed","boyar","brack","brake","brand",
        "brant","brats","braza","break","breed","brent","breve","broad","broke","brule",
        "brume","bubby","bugle","bulge","bumph","bunch","bunco","buppy","bused","butte",
        "butyl","buzzy","byway","cabal","cadge","calix","calve","campy","canid","canoe",
        "canto","carby","carer","caret","cesta","chafe","chary","chela","chert","chevy",
        "chide","chino","chirp","chits","civvy","clade","claps","cleek","cloak","clops",
        "clots","clued","clunk","coact","coifs","coign","comal","combo","comfy","conch",
        "conge","conte","cooky","copse","corgi","corky","covin","coxed","creak","credo",
        "creep","crept","crick","cried","crier","criss","croup","crowd","cruse","cubic",
        "curly","cutup","cycad","cyder","cylix","daffy","decaf","decal","decay","decry",
        "defer","deify","deign","demur","dicey","dingo","dippy","ditzy","divan","doggy",
        "dolce","domed","dopey","dowel","droit","duchy","ducky","duped","dusky","dusty",
        "duvet","dwelt","earns","emote","enact","epoxy","ethic","etude","evoke","exude",
        "fagot","fatly","faugh","fawny","faxed","fazed","feaze","fecal","feral","flaps",
        "flunk","fogey","folio","fosse","frond","fugal","funky","ganef","garth","gavel",
        "glogg","gloze","glued","golem","gonzo","grail","graze","grill","grout","gulch",
        "haiku","halon","harpy","helix","helot","herby","hoary","hogan","hooch","hotly",
        "humus","ictus","idyll","incus","inure","iodin","itchy","jabot","jenny","jerky",
        "jihad","joule","julep","junto","kabob","kafir","kerfs","khaki","knobs","labra",
        "larum","leach","legit","levin","loath","lymph","mafia","maize","mangy","maxed",
        "melee","mitre","minim","moray","mucky","mulch","munge","napes","nitid","nonce",
        "nooks","nosey","novae","nudge","ochre","offal","optic","orate","paddy","paled",
        "pally","pangs","pasty","pawky","peeve","petty","plink","polyp","ponce","potty",
        "prink","prosy","proxy","pudge","pulpy","pushy","quasi","racer","raile","rayon",
        "rebus","rebuy","recut","refit","remit","renew","riced","riled","rowan","saber",
        "sagas","seamy","shady","shake","shall","shalt","sheen","silky","slick","sloop",
        "spoil","spoke","staid","stoma","suety","sunup","surly","swath","swipe","synod",
        "taboo","tacit","tanka","taupe","tawse","thigh","tibia","towny","turbo","twerp",
        "unban","uncap","unrig","unsay","unzip","uteri","varve","vapid","venal","vexed",
        "vigil","vireo","vocab","voile","volte","yokel","zooid","zippy","zappy","blini",
        "creak","fizzy","funky","abele","aceta","acini","adhan","ajuga","alary","alate",
        "alays","alecs","alfas","algas","algae","algal","alowe","amain","anted","antes",
        "apian","ariel","arils","armet","arras","arris","arums","arval","arvos","atilt",
        "atman","audad","aurae","aurar","autre","auxin","avion","aviso","awing","axile",
        "axled","azide","azine","azole","azote","azoth","boule","boyar","braze","brell",
        "breve","brill","brims","brins","brios","calix","carby","cesta","chela","chert",
        "chide","chiro","chits","chive","chivy","civvy","clads","claes","clags","clams",
        "clans","cleek","coaly","cobby","coble","codex","codon","coeds","coley","colly",
        "colts","comae","combe","combs","comer","comes","comte","conus","coots","coped",
        "coper","cores","coria","corks","corns","corse","coset","cosey","cosie","costa",
        "cotan","coude","cozen","crabs","crags","crams","craps","crare","craws","crays",
        "cress","creux","crews","cribs","cripe","crocs","crops","crost","croud","cruve",
        "cubby","culet","culls","cully","culms","cuppa","curbs","curds","curia","curie",
        "curns","cushy","cutey","cyclo","cymae","cymas","cymes","cyton","davit","deify",
        "diact","dicot","droit","duchy","duels","earst","egged","elbow","embar","embow",
        "embus","emend","emery","emeus","emirs","emmet","emote","emyde","endue","enorm",
        "ensue","epact","epode","ergot","faery","famed","fards","fared","fares","fasti",
        "fated","fates","fatwa","fauld","fauns","fause","fauts","favar","favel","faves",
        "favus","fayed","fazes","feoff","ferly","fermi","ferns","ferny","fiats","fiend",
        "fifed","fifer","fifes","figged","filed","files","fills","filmy","filos","flabs",
        "flaky","flamy","flawy","flays","fleas","fleek","fleys","flier","flirs","flocs",
        "flogs","flora","flors","floss","flour","flubs","flued","flues","fluey","flunk",
        "fogle","foids","fomes","fonly","foots","foram","forbs","forel","foret","forky",
        "forme","forme","found","foyer","frabs","frack","fracs","fract","frags","frain",
        "frais","freak","freed","frees","frent","freon","frets","frigs","frisk","frith",
        "frits","fritz","frize","frizz","froe","froze","frump","fubar","fumed","fumer",
        "fumes","fumet","funic","funks","furan","furls","fusel","fussy","fytte",
        "gamba","gambe","gamic","gamed","gamer","games","gamey","gamic","garbs","garni",
        "gauds","gault","gazer","gazed","gazes","geeks","genic","genip","genoa","gibed",
        "giber","gibes","giddy","gilet","girds","girts","glads","glams","glans","glary",
        "gleds","gleed","glees","gleis","glens","glued","gluer","glues","gluey","gnawn",
        "gonef","gored","gores","goris","gorps","grabs","grads","grays","grids","griot",
        "gript","grisy","groan","grody","groks","grume","gryde","guano","guild","guiro",
        "gulag","gulls","gully","gumma","gunky","gwine","gybed","gybes","gyron","gyrus",
        "hadal","haded","hades","hadj","haems","haets","haiks","hamal","hames","hamza",
        "hanap","hards","harls","hasks","hayey","hazed","hazes","heiau","heiau","hejab",
        "helve","hemal","herbs","herby","heroe","hertz","hests","hiked","hikes","hilar",
        "hillo","hilsa","hiree","hived","hives","hoaed","hoked","hokes","holks","holms",
        "holts","hoped","hoper","hoped","horal","horde","horns","hosel","hoten","hovel",
        "hoven","howff","huffy","hyoid","impis","inane","incog","infix","ingot","inkle",
        "inker","inked","inlay","inlet","irone","irons","irony","isled","isles","islet",
        "jalap","jambe","jambs","janty","jatos","jaups","jazzy","jebel","jerid","jetes",
        "jihad","jibed","jiber","jibes","jingo","jiney","jived","jives","jokey","jones",
        "joual","joule","joust","juked","jukes","julep","jumby","junto","jurel","kabar",
        "kades","kafir","kaiak","kaika","kanji","karst","kefir","kerfs","kevel","kibes",
        "kiddo","kilts","kinas","kinks","knurl","kofta","kopek","kophs","korun","kraal",
        "kraut","labia","lacet","lahar","laich","laiks","laird","laked","laker","laked",
        "lakhs","lamas","lanai","laree","lares","largo","larum","lassi","laved","laves",
        "lawks","lawny","laxly","lazed","lazes","leapt","leben","lemma","lepid","letch",
        "liana","liard","libra","lidar","liens","lifer","liffy","ligne","lilos","lined",
        "liner","linin","lisle","litho","lived","liven","livid","llano","lobos","locos",
        "locum","loden","lorel","lorry","lotsa","lough","lours","louts","lunar","lurex",
        "lusus","luted","luter","lutes","lutea","luxes","lyase","lyric",
        "mabes","macer","maces","maile","mails","mains","maist","maker","malar","males",
        "malls","malts","malty","mambo","mamba","maned","manga","mangy","manic","manus",
        "marae","marcs","mares","marka","marls","marly","maror","masse","mased","maser",
        "mases","matey","matin","matts","maund","mauts","mazed","mazer","mazes","meads",
        "mealy","meany","metic","meths","metis","mewed","mewls","micra","midis","milds",
        "miles","milpa","minae","minke","mirin","misdo","mises","missy","mitre","mixed",
        "mixes","mocha","moils","moira","molto","monks","moody","moral","morel","morns",
        "moron","morph","mousy","moxie","mucro","mudra","mulct","mulls","mumps","murra",
        "nairu","naked","napes","nappe","narco","nards","naris","natty","navar","navvy",
        "nears","neats","neifs","nervy","netop","netts","ngaio","ngana","ngati","nicol",
        "niffs","nimbi","nimby","nines","nippy","nixie","noble","noels","nomas","nomas",
        "nomoi","nopal","nopals","norks","noter","novas","novum","numbs","nuns","nyaff",
        "oakum","oaves","obeah","obeys","oboli","obols","oddly","odeum","odist","odium",
        "oinks","okras","oleum","olios","omens","omers","omits","oophs","orgue","oribi",
        "ornis","ovolo","oxbow","oxeye","oyers","paced","pacer","paces","padis","paged",
        "pager","pages","pagod","paiks","pails","pated","paten","pater","patin","peans",
        "pearl","pelts","perdu","perky","perms","pipit","plasm","plats","playa","pleas",
        "plied","plier","plods","plots","plows","ploys","plumb","plume","plump","plunk",
        "poncy","poohs","porgy","presa","prest","pryer","psych","pubis","pudge","puggy",
        "pugil","punky","punny","punto","pupal","pupil","purls","pyres","pyrex",
        "rabic","rails","raita","rakee","rales","ramen","ramie","ranee","ratel","rawly",
        "reais","reaks","reals","reamy","reave","rebec","rebid","reeks","reely","reeve",
        "reify","reiki","reins","rejig","rekey","relax","remex","repro","rerig","resaw",
        "retag","rewan","rewax","rewed","rewet","rewon","rhumb","rials","riata","ridgy",
        "rioja","rishi","risus","ruche","rugae","rugal","rugby","ruled","ruler","rumen",
        "runic","runts","runty","ryots",
        "sabin","sabot","sades","sadis","safes","saggy","sahib","saiga","saint","saker",
        "salep","sambo","samek","sapor","sarky","sassy","seamy","sebum","senna","senvy",
        "sepal","serge","shads","shags","shakt","shaly","sharn","sheal","sheas","shels",
        "shlep","shmos","shoat","shorl","shorn","shott","shrub","shunts","sidhe","sieur",
        "sigil","sigla","silts","siren","sirra","sirup","sisal","sixth","sixte","skald",
        "skell","skied","skied","skiey","skrip","skrit","sloam","sloes","sloid","slops",
        "slors","slung","slunk","smalt","smolt","snags","snaps","snath","snobs","snobs",
        "snoep","snoep","snogs","snoot","snore","snorl","snubs","soddy","softa","softs",
        "sokah","soken","sokol","solan","sonly","sonly","sooty","sorns","sorrel","sotol",
        "spado","spald","spale","spall","spang","spate","spean","spect","speel","speer",
        "speil","speir","spero","spiff","spile","spilt","stime","stimy","stoep","stogy",
        "stoln","stoma","stomy","stony","stour","stown","stray","strew","strob","stroam",
        "stroy","sudor","sudsy","suety","sufis","sulfa","sunna","sunup","sunly","supra",
        "surds","surfy","syrup",
        "tabor","takis","talar","taled","taler","tales","talon","talpa","tanga","tansy",
        "tapas","tapis","targe","tarns","tarns","tarre","tarry","tasse","tater","tauon",
        "taupe","tauts","tawse","taxon","tayra","tazes","teals","terce","thack","thane",
        "theca","thein","thens","theta","thews","thins","those","thro","throe","thuya",
        "tical","tical","tilts","times","tippy","tirrs","tithe","togae","togue","toile",
        "toles","tolls","tombs","tondo","tonga","tongs","torcs","torte","totem","toyon",
        "trabs","trawl","tribs","trice","trill","trims","tripe","troth","trows","trued",
        "truer","trugs","trull","tryma","tsadi","tuath","tubas","tubed","tuber","turfs",
        "twerp","twice","tyers","tykes","typal","tyrant",
        "uhlan","ulans","ulnar","ulnas","umber","umbra","umped","ungot","unpeg","unpen",
        "unpeg","unrig","unset","unwed","uraei","urare","urase","urate","uredo","urial",
        "uriel","ursal","uteri","uveal","uveas",
        "vaunt","veery","veldt","venge","vetch","viand","virtu","visas","vroom",
        "waded","wader","wades","wadis","waged","wager","wages","walts","wamed","wases",
        "washy","wavey","wayed","weald","weens","weepy","welts","whang","whaps","whats",
        "wheal","whens","whet","whets","whews","wheys","while","whims","whing","whins",
        "whips","whirl","whish","whist","whits","whizz","whomp","wides","wiled","wiles",
        "wince","winze","wiped","wiper","wipes","woful","wombs","wooer","wormy","wroth",
        "wuther","wyted","wytes",
        "xebec","xeric","xerus",
        "yauds","yawls","yawns","yawp","yenta","yente","yipes","yokel","yodle","yores",
        "yourn","yowls","yugas","zaire","zakat","zills","zincs","zinky","zippy","zloty",
        "zoeas","zombi","zonae","zoned","zoner","zones","zonks","zooid","zooms","zooks",
        "zoeae","zoeal","zoeas",
    ]

    // MARK: - Combined word set used for guess validation
    static var allowedWords: [String] { possibleAnswers + additionalGuesses }

    // MARK: - Backward-compatible aliases (WordleGame.swift uses these names)
    static var answers: [String] { possibleAnswers }
    static var allWords: [String] { allowedWords }
}
