    // MARK: - Possible answer words (v2, independently sourced)
    static let possibleAnswers: [String] = [
        // A
        "aback","abbey","abbot","abide","abode","abort","about","above","abuse","abyss",
        "acorn","actin","acton","actor","acute","adage","adapt","added","adept","adieu",
        "admin","admit","adobe","adopt","adore","adorn","adult","aegis","afoot","after",
        "again","agate","agent","agile","aging","agony","agree","ahead","aisle","alamo",
        "alarm","album","alder","alert","algae","alias","alibi","alien","align","alike",
        "alive","alkyl","allan","alley","allow","alloy","aloft","alone","along","aloof",
        "aloud","alpha","altar","alter","amaze","amber","amend","amino","amiss","amity",
        "amman","among","amour","ample","amuse","angel","anger","angle","angry","angst",
        "anime","ankle","annex","annoy","anode","anvil","aorta","apart","apnea","apple",
        "apply","apron","aptly","arbor","arena","arent","argon","argue","ariel","arise",
        "arjun","armed","armor","aroma","arose","array","arrow","arson","ascii","ascot",
        "ashes","aside","aspen","assay","asset","aster","astor","atlas","atoll","atone",
        "attic","audio","audit","avail","avert","avian","avoid","await","awake","award",
        "aware","awful","awoke","axial","axiom","azure",
        // B
        "bacon","badge","badly","bafta","bagel","baggy","baked","baker","banal","banco",
        "banda","banjo","barge","baron","barra","barry","barth","basal","based","basic",
        "basil","basin","basis","batch","bathe","baton","bayou","beach","beard","beast",
        "bebop","beech","begin","begun","beige","being","belle","belly","below","bench",
        "benny","beret","berry","berth","beryl","beset","betty","bezel","bigot","bilbo",
        "billy","binge","bingo","birch","birth","bison","black","blade","blair","blake",
        "blame","blanc","bland","blank","blast","blaze","bleak","bleed","blend","bless",
        "blind","blink","bliss","blitz","block","bloke","blood","bloom","blown","bluff",
        "blunt","blush","board","boast","bobby","bogey","bogus","boned","bongo","bonny",
        "bonus","booby","boost","booth","booty","booze","borne","boron","bosch","bosom",
        "bossy","bound","bowed","bowel","bower","bowie","boxer","boyer","brace","braid",
        "brain","brake","brand","brant","brash","brass","brave","bravo","brawl","bread",
        "break","breed","brent","brett","briar","bribe","brick","bride","brief","brill",
        "brine","bring","brink","brisk","broad","brock","broke","brood","brook","broom",
        "broth","brown","brunt","brush","brute","bucky","buddy","budge","buffy","buggy",
        "bugle","build","built","bulge","bulky","bully","bumpy","bunch","bundy","bunny",
        "burgh","burke","burly","burnt","burst","bushy","butch","butte","buyer",
        // C
        "cabal","cabin","cable","cabot","cacao","cache","caddy","cadet","cadre","caged",
        "cairn","cajun","camel","cameo","campo","camus","canal","candy","canny","canoe",
        "canon","canto","caper","carat","carer","cargo","carol","carry","carte","carve",
        "caste","catch","cater","cause","cease","cedar","cello","chain","chair","chalk",
        "champ","chang","chant","charm","chart","chase","chasm","cheap","cheat","check",
        "cheek","cheer","cheng","chess","chest","chevy","chewy","chick","chico","chief",
        "child","chile","chili","chill","chime","china","ching","chino","chock","choir",
        "choke","chord","chore","chose","chuck","chump","chunk","churn","chute","cider",
        "cigar","circa","cisco","civic","civil","claim","clamp","clark","clash","clasp",
        "class","clean","clear","cleft","clerk","click","cliff","climb","cline","cling",
        "clint","clive","cloak","clock","clone","close","cloth","cloud","clout","clove",
        "clown","clump","clung","coach","coast","cobra","cocky","cocoa","codex","colin",
        "colon","color","comer","comet","comfy","comic","comma","conte","coral","corgi",
        "corny","costa","cotta","couch","cough","could","count","coupe","court","cover",
        "covet","covid","crack","craft","cramp","crane","crank","crash","crass","crate",
        "crave","crawl","craze","crazy","cream","creed","creek","creep","crepe","crept",
        "crest","crick","cried","crime","crisp","criss","crock","croft","crook","crore",
        "cross","crowd","crown","crude","cruel","crumb","crush","crust","crypt","cubic",
        "cumin","curie","curly","curry","curse","curve","curvy","cutie","cycle","cynic",
        "cyrus",
        // D
        "daddy","daily","dairy","daisy","dance","dandy","darby","dazed","dealt","death",
        "debit","debut","decal","decay","decoy","defer","deity","delay","delta","delve",
        "demon","demos","denim","dense","depot","depth","derby","derry","deter","deuce",
        "devil","dhoni","diary","diddy","didnt","digit","diner","dingy","diode","dirty",
        "ditch","ditto","diver","dixie","dizzy","dodge","dodgy","doggo","doggy","dogma",
        "doing","dolly","donna","donor","doubt","dough","dover","dowry","dozen","draft",
        "drain","drake","drama","drank","drawn","dread","dream","dress","dried","drier",
        "drift","drill","drink","drive","drone","drool","drove","drown","druid","duchy",
        "dunne","duper","dusky","dusty","dutch","duvet","dwarf","dwell","dying",
        // E
        "eager","eagle","eared","early","earth","eaten","eater","ebony","edema","edged",
        "edict","eerie","eight","eject","elbow","elder","elect","elite","elves","embed",
        "ember","emery","emmet","empty","enact","ended","enema","enemy","enjoy","ensue",
        "enter","entry","envoy","epoch","equal","equip","erase","erika","erode","error",
        "erupt","essay","ester","ethel","ether","ethic","ethos","ethyl","evade","event",
        "every","evict","evoke","exact","excel","exert","exile","exist","expel","extra",
        // F
        "fable","faced","facet","faded","faint","fairy","faith","faker","false","fancy",
        "farce","fatal","fated","fatty","fault","faust","favor","feast","fecal","feces",
        "felon","femur","fence","feral","ferry","fetal","fetch","fetus","fever","fiber",
        "field","fiend","fiery","fifth","fifty","fight","filet","filly","filth","final",
        "finch","finer","fired","first","firth","fishy","fitch","fixed","fixer","fizzy",
        "flack","flair","flake","flaky","flame","flank","flare","flash","flask","fleet",
        "flesh","flick","flier","fling","flint","flirt","float","flock","flood","floor",
        "flora","floss","flour","flown","fluff","fluid","fluke","flume","flung","flush",
        "flute","flyer","focal","focus","foggy","folio","folly","footy","foray","force",
        "forge","forgo","forte","forth","forty","forum","found","foyer","frail","frame",
        "franc","frank","fraud","freak","freed","freer","fresh","friar","fried","frisk",
        "frock","front","frost","frown","froze","fruit","fryer","fudge","fully","fungi",
        "funky","funny","furry","fused","fussy","fuzzy",
        // G
        "gabby","gable","gamma","gamut","ganga","garth","gated","gator","gaudy","gauge",
        "gaunt","gauss","gauze","gecko","geese","gemma","genie","genre","ghost","ghoul",
        "giant","giddy","ginny","girly","girth","given","giver","gland","glare","glass",
        "glaze","gleam","glide","globe","gloom","glory","gloss","glove","glued","gnome",
        "godly","going","goody","goofy","goose","goran","gorge","gourd","grace","grade",
        "graff","graft","grail","grain","grand","grant","grape","graph","grasp","grass",
        "grate","grave","gravy","graze","great","greed","green","greet","grief","grill",
        "grime","grind","gripe","groan","groin","groom","groot","gross","group","grout",
        "grove","growl","grown","gruff","grunt","guard","guess","guest","guide","guild",
        "guilt","guise","gully","gummy","gusto","gypsy",
        // H
        "habit","hairy","hakim","halal","hamza","handy","hanna","happy","hardy","harem",
        "harry","harsh","hasan","haste","hasty","hatch","hater","haunt","haven","havoc",
        "hazel","heady","heart","heath","heave","heavy","hedge","hefty","helix","hello",
        "hence","henna","henry","heron","hertz","hilly","hinge","hippo","hippy","hired",
        "hitch","hoard","hobby","hogan","hoist","holly","homer","honda","honey","honor",
        "hoped","horde","horse","horst","hotel","hotly","hough","hound","house","hover",
        "howdy","hubby","human","humid","humor","hunch","huron","hurry","hurst","husky",
        "hutch","hydro","hyena","hyper",
        // I
        "icing","ideal","idiom","idiot","image","imply","incur","index","inept","inert",
        "infer","infra","inlet","inner","input","inset","inter","ionic","irene","irony",
        "issue","itchy","ivory",
        // J
        "jaded","japan","jazzy","jelly","jenna","jenny","jerky","jerry","jetty","jewel",
        "jihad","jimmy","joint","joker","jolly","josie","judge","juice","juicy","julio",
        "jumbo","junta","juror",
        // K
        "kappa","karma","kayak","kebab","kelly","kerry","keyed","khaki","kiosk","kitty",
        "knack","kneel","knelt","knife","knock","knoll","known","koala","kodak","kraft",
        "kudos",
        // L
        "label","labor","laced","laden","lager","laird","laker","lance","lapse","large",
        "largo","larry","larva","laser","latch","later","latex","lathe","laugh","laura",
        "layer","lazar","leach","leafy","leaky","leapt","learn","lease","leash","least",
        "leave","ledge","leech","legal","legit","lemon","level","lever","levin","lewis",
        "liang","libel","liber","libra","liege","light","lilac","limbo","limit","lined",
        "linen","liner","lingo","liter","lived","liver","livid","llama","lobby","local",
        "locus","lodge","lofty","logic","login","lohan","lolly","loose","lorry","loser",
        "lotto","lotus","lough","lousy","lover","lower","lowly","loyal","lucid","lucky",
        "lumen","lumpy","lunar","lunch","lunge","lupus","lying","lymph","lynch","lyric",
        // M
        "macao","macro","madam","madly","magic","magma","maize","major","maker","malik",
        "mamma","manga","mango","mania","manic","manly","manna","manny","manor","manta",
        "manus","maple","march","marco","marge","maria","marry","marsh","mason","masse",
        "match","mater","matte","mavis","maxim","maybe","mayor","meant","meaty","medal",
        "media","medic","melee","melon","merch","mercy","merge","merit","merle","merry",
        "messy","metal","meter","micro","midst","might","milky","mille","mimic","mince",
        "miner","minor","minus","mirza","missy","misty","mixed","mixer","mocha","modal",
        "model","moist","molar","molly","mommy","money","monte","month","moody","moose",
        "moral","moray","morph","morse","motel","motif","motor","motto","mould","mound",
        "mount","mourn","mouse","mouth","mover","movie","mower","mucus","muddy","mufti",
        "mulch","mummy","munch","mural","murky","mushy","music","musty","myron",
        // N
        "nadir","naive","nancy","nanny","nasal","nasty","natal","naval","navel","neath",
        "needy","nerve","never","newly","nexus","niche","nicky","niece","nifty","night",
        "ninth","nitro","noble","noise","noisy","nomad","noose","norma","north","nosed",
        "notch","noted","novel","nudge","nurse","nutty","nylon","nymph",
        // O
        "oasis","obese","occur","ocean","oddly","offer","often","oiled","olden","older",
        "olive","omega","onion","onset","opera","optic","orbit","order","ortho","other",
        "otter","ought","ounce","outed","outer","overt","owing","owner","oxide","ozone",
        // P
        "pablo","paced","padre","pagan","paint","paler","palma","palsy","panda","panel",
        "panic","paolo","papal","paper","parma","parry","parse","party","pasha","paste",
        "patch","patel","patio","patty","pause","payed","payer","peace","peach","pearl",
        "pecan","pedal","pedro","peeve","peggy","penal","pence","penny","perch","peres",
        "peril","perky","perry","pesky","petal","peter","petit","petty","phase","phone",
        "phony","photo","piano","picky","piece","piety","piggy","pilar","piled","pilot",
        "pinch","pinky","pinto","pious","piped","piper","pique","pitch","pivot","pixie",
        "pizza","place","plaid","plain","plane","plank","plant","plate","playa","plaza",
        "plead","pluck","plumb","plume","plump","plush","point","poise","poked","poker",
        "polar","polio","polka","ponce","pooch","poppy","porch","porta","porto","posey",
        "posse","pouch","pound","power","prank","prawn","press","price","pride","prima",
        "prime","print","prior","prism","prius","privy","prize","probe","prone","prong",
        "proof","prose","proto","prove","proxy","prune","psalm","psych","puffy","pulse",
        "punch","punta","pupil","puppy","purdy","puree","purge","purse","putty",
        // Q
        "quack","quail","quake","quark","quart","quasi","queen","quell","query","quest",
        "queue","quick","quiet","quill","quilt","quirk","quite","quota","quote",
        // R
        "rabbi","rabid","racer","radar","radio","radon","rainy","raise","rally","ralph",
        "ranch","randy","range","rapid","rated","ratio","raven","rayon","razer","razor",
        "reach","react","ready","realm","rebel","recap","recon","reddy","reese","reeve",
        "refer","regal","reign","reina","relax","relay","relic","remit","remix","renal",
        "renew","repay","repel","reply","rerun","reset","resin","reuse","revel","rhine",
        "rhino","rhyme","rider","ridge","rifle","right","rigid","rigor","riley","rinse",
        "risen","riser","risky","rival","river","roach","roast","robin","robot","rocky",
        "rodeo","rogan","roger","rogue","rohan","rondo","roost","roper","rotor","rouge",
        "rough","round","rouse","route","rover","rowan","rowdy","rower","royal","ruddy",
        "rufus","ruler","rumor","runny","rupee","rural","rusty","ryder",
        // S
        "saber","sable","sadly","sahib","saint","salad","salle","sally","salon","salty",
        "salve","salvo","samba","sammy","sandy","sassy","satan","satin","sauce","saucy",
        "sauna","saved","saver","savor","savoy","savvy","sawed","scala","scale","scalp",
        "scaly","scant","scare","scarf","scary","scene","scent","scion","scold","scoop",
        "scope","score","scorn","scour","scout","scrap","scrub","scrum","sedan","seedy",
        "seine","seize","senna","sense","serge","serra","serum","serve","servo","seton",
        "setup","seven","sever","sewed","sewer","shack","shade","shady","shaft","shake",
        "shaky","shale","shall","shalt","shame","shank","shape","shard","share","shark",
        "sharp","shave","shawl","shear","sheen","sheep","sheer","sheet","sheik","shelf",
        "shell","sheng","shift","shine","shiny","shire","shirt","shoal","shock","shone",
        "shook","shoot","shore","short","shout","shove","shown","shred","shrub","shrug",
        "shunt","sided","siege","sieve","sight","sigma","silky","silly","silva","since",
        "singh","sinus","siren","sixth","sixty","sized","skate","skier","skies","skill",
        "skirt","skull","skunk","slack","slade","slain","slang","slant","slash","slate",
        "sleek","sleep","sleet","slept","slice","slick","slide","slime","slimy","sling",
        "sloan","sloop","sloth","slump","slung","slush","smack","small","smart","smash",
        "smear","smell","smelt","smile","smirk","smite","smith","smoke","smoky","smyth",
        "snack","snail","snake","snape","snare","sneak","snell","sniff","snipe","snoop",
        "snort","snout","snowy","snuck","sober","soggy","solar","solid","solve","sonar",
        "sonic","sonny","sorry","sound","south","space","spade","spank","spare","spark",
        "spasm","spawn","speak","spear","speck","speed","spell","spelt","spend","spent",
        "spice","spicy","spied","spike","spill","spilt","spine","spire","spite","split",
        "spoil","spoke","spoof","spook","spool","spoon","spore","sport","spout","spray",
        "spree","spurt","squad","squat","squid","stack","staff","stage","stain","stair",
        "stake","stale","stalk","stall","stamp","stand","stare","stark","start","stash",
        "state","stave","stead","steak","steal","steam","steed","steel","steep","steer",
        "stein","stent","stern","stick","stiff","still","sting","stink","stint","stock",
        "stoic","stoke","stole","stomp","stone","stony","stood","stool","stoop","store",
        "stork","storm","story","stout","stove","strap","straw","stray","strut","stuck",
        "study","stuff","stump","stung","stunt","style","suave","suede","sugar","suing",
        "suite","sully","sunny","super","surat","surge","surly","sutra","swain","swami",
        "swamp","swarm","swath","swear","sweat","sweep","sweet","swell","swept","swift",
        "swine","swing","swipe","swirl","swish","swiss","swoon","swoop","sword","swore",
        "sworn","swung","synod","syrup",
        // T
        "table","taboo","tacit","tacky","taint","taken","taker","takin","tally","talon",
        "tammy","tango","tania","taper","tarot","taste","tasty","taunt","taxed","teach",
        "teary","tease","teeny","teeth","tempo","tempt","tenet","tenor","tense","tenth",
        "terry","thane","thank","theft","their","theme","there","these","theta","thick",
        "thief","thigh","thine","thing","think","third","thong","thorn","those","three",
        "threw","throw","thumb","thump","thyme","tiara","tibet","tibia","tidal","tiger",
        "tight","tiled","tilly","timed","timer","timid","timor","tinge","tipsy","tired",
        "tithe","title","toast","today","token","tommy","tonal","toned","toner","tonga",
        "tonic","tooth","topaz","topic","torah","torch","torso","total","totem","touch",
        "tough","towel","tower","toxic","toxin","trace","track","tract","trade","trail",
        "train","trait","trash","tread","treat","trend","triad","trial","tribe","trick",
        "tried","trier","trite","troll","troop","trope","trout","trove","truce","truck",
        "truer","truly","trump","trunk","truss","trust","truth","tulip","tummy","tumor",
        "tuned","tuner","tunic","turbo","tutor","twain","tweak","tweed","tween","tweet",
        "twice","twine","twink","twist","tying",
        // U
        "ulcer","ultra","uncle","uncut","under","undue","unfit","unify","union","unite",
        "unity","until","upper","upset","urban","usage","usher","usual","utter",
        // V
        "vague","valet","valid","valor","value","valve","vapor","vault","venom","venue",
        "verge","verse","verve","vexed","vicar","video","vigil","vigor","villa","ville",
        "vinny","vinyl","viola","viper","viral","virus","visit","visor","vista","vital",
        "vivid","vocal","vogue","voice","voter","vouch","vowed","vowel","vying",
        // W
        "wacky","wafer","waged","wager","wagon","waist","waive","wally","walsh","waltz",
        "waned","wasnt","waste","watch","water","waugh","waved","weary","weave","weber",
        "wedge","weigh","weird","welsh","whack","whale","wharf","wheat","wheel","where",
        "which","whiff","while","whine","whiny","whirl","whisk","white","whole","whoop",
        "whose","widen","widow","width","wield","wigan","wight","winch","windy","wiper",
        "wired","wiser","witch","witty","woman","wonky","world","worry","worse","worst",
        "worth","would","wound","woven","wrath","wreak","wreck","wrist","write","wrong",
        "wrote",
        // X
        "xenon",
        // Y
        "yacht","yahoo","yearn","yeast","yield","young","youth","youve","yummy",
        // Z
        "zebra","zoned",
    ]
