    // MARK: - Possible answer words (HARD variant, independently sourced)
    static let possibleAnswers: [String] = [
        // A
        "aback","abbey","abbot","abide","abode","abort","abyss","acorn","actin","acton",
        "acute","adage","adapt","adept","adieu","admin","adobe","adopt","adore","adorn",
        "aegis","afoot","agate","agile","aging","agony","aisle","alamo","alarm","alder",
        "alert","algae","alias","alibi","alien","align","alike","alkyl","allan","alley",
        "alloy","aloft","aloof","aloud","alpha","altar","alter","amaze","amber","amend",
        "amino","amiss","amity","amman","amour","ample","amuse","angle","angst","anime",
        "ankle","annex","annoy","anode","anvil","aorta","apnea","apron","aptly","arbor",
        "arena","arent","argon","ariel","arise","arjun","armor","aroma","arose","array",
        "arrow","arson","ascii","ascot","ashes","aspen","assay","asset","aster","astor",
        "atlas","atoll","atone","attic","audit","avail","avert","avian","await","awake",
        "awoke","axial","axiom","azure",
        // B
        "bacon","badge","bafta","bagel","baggy","baked","baker","banal","banco","banda",
        "banjo","barge","baron","barra","barry","barth","basal","basil","basin","batch",
        "bathe","baton","bayou","beard","beast","bebop","beech","begun","beige","belle",
        "belly","bench","benny","beret","berry","berth","beryl","beset","betty","bezel",
        "bigot","bilbo","billy","binge","bingo","birch","bison","blade","blair","blake",
        "blanc","bland","blank","blast","blaze","bleak","bleed","blend","bless","blink",
        "bliss","blitz","bloke","bloom","blown","bluff","blunt","blush","boast","bobby",
        "bogey","bogus","boned","bongo","bonny","booby","booth","booty","booze","borne",
        "boron","bosch","bosom","bossy","bowed","bowel","bower","bowie","boxer","boyer",
        "brace","braid","brake","brant","brash","brass","brave","bravo","brawl","breed",
        "brent","brett","briar","bribe","brick","bride","brill","brine","brink","brisk",
        "brock","brood","brook","broom","broth","brunt","brush","brute","bucky","budge",
        "buffy","buggy","bugle","bulge","bulky","bully","bumpy","bundy","bunny","burgh",
        "burke","burly","burnt","burst","bushy","butch","butte","buyer",
        // C
        "cabal","cabin","cabot","cacao","cache","caddy","cadet","cadre","caged","cairn",
        "cajun","camel","cameo","campo","camus","canal","candy","canny","canoe","canon",
        "canto","caper","carat","carer","cargo","carol","carte","carve","caste","cater",
        "cease","cedar","cello","chalk","champ","chang","chant","charm","chasm","cheat",
        "cheek","cheer","cheng","chess","chevy","chewy","chick","chico","chile","chili",
        "chill","chime","ching","chino","chock","choir","choke","chord","chore","chuck",
        "chump","chunk","churn","chute","cider","cigar","circa","cisco","civic","clamp",
        "clark","clash","clasp","cleft","clerk","cliff","climb","cline","cling","clint",
        "clive","cloak","clone","cloth","clout","clove","clown","clump","clung","cobra",
        "cocky","cocoa","codex","colin","colon","comer","comet","comfy","comma","conte",
        "coral","corgi","corny","costa","cotta","couch","cough","coupe","covet","covid",
        "craft","cramp","crane","crank","crass","crate","crave","crawl","craze","creed",
        "creek","creep","crepe","crept","crest","crick","cried","crisp","criss","crock",
        "croft","crook","crore","crude","cruel","crumb","crush","crust","crypt","cubic",
        "cumin","curie","curly","curry","curse","curve","curvy","cutie","cynic","cyrus",
        // D
        "daddy","dairy","daisy","dandy","darby","dazed","dealt","debit","decal","decay",
        "decoy","defer","deity","delta","delve","demon","demos","denim","dense","depot",
        "derby","derry","deter","deuce","devil","dhoni","diary","diddy","didnt","digit",
        "diner","dingy","diode","ditch","ditto","diver","dixie","dizzy","dodge","dodgy",
        "doggo","doggy","dogma","dolly","donna","donor","dough","dover","dowry","dozen",
        "drain","drake","drank","dread","dried","drier","drift","drill","drone","drool",
        "drove","drown","druid","duchy","dunne","duper","dusky","dusty","duvet","dwarf",
        "dwell",
        // E
        "eager","eagle","eared","eaten","eater","ebony","edema","edged","edict","eerie",
        "eject","elbow","elder","elect","elves","embed","ember","emery","emmet","enact",
        "enema","ensue","envoy","epoch","equip","erase","erika","erode","erupt","essay",
        "ester","ethel","ether","ethic","ethos","ethyl","evade","evict","evoke","excel",
        "exert","exile","expel",
        // F
        "fable","facet","faded","faint","fairy","faker","fancy","farce","fatal","fated",
        "fatty","faust","feast","fecal","feces","felon","femur","fence","feral","ferry",
        "fetal","fetch","fetus","fever","fiber","fiend","fiery","fifty","filet","filly",
        "filth","finch","finer","firth","fishy","fitch","fixer","fizzy","flack","flair",
        "flake","flaky","flame","flank","flare","flask","fleet","flesh","flick","flier",
        "fling","flint","flirt","float","flock","flood","flora","floss","flour","flown",
        "fluff","fluid","fluke","flume","flung","flush","flute","flyer","focal","foggy",
        "folio","folly","footy","foray","forge","forgo","forte","forty","forum","foyer",
        "frail","franc","fraud","freak","freed","freer","friar","fried","frisk","frock",
        "frost","frown","froze","fryer","fudge","fungi","funky","furry","fused","fussy",
        "fuzzy",
        // G
        "gabby","gable","gamma","gamut","ganga","garth","gated","gator","gaudy","gauge",
        "gaunt","gauss","gauze","gecko","geese","gemma","genie","genre","ghoul","giddy",
        "ginny","girly","girth","giver","gland","glare","glaze","gleam","glide","globe",
        "gloom","glory","gloss","glove","glued","gnome","godly","goody","goofy","goose",
        "goran","gorge","gourd","graff","graft","grail","grain","grape","graph","grasp",
        "grass","grate","grave","gravy","graze","greed","greet","grief","grill","grime",
        "grind","gripe","groan","groin","groom","groot","grout","grove","growl","gruff",
        "grunt","guild","guilt","guise","gully","gummy","gusto","gypsy",
        // H
        "habit","hairy","hakim","halal","hamza","handy","hanna","hardy","harem","harsh",
        "hasan","haste","hasty","hatch","hater","haunt","haven","havoc","hazel","heady",
        "heath","heave","hedge","hefty","helix","hence","henna","heron","hertz","hilly",
        "hinge","hippo","hippy","hitch","hoard","hobby","hogan","hoist","holly","homer",
        "honda","honey","hoped","horde","horst","hotly","hough","hound","hover","howdy",
        "hubby","humid","humor","hunch","huron","hurry","hurst","husky","hutch","hydro",
        "hyena","hyper",
        // I
        "icing","idiom","idiot","imply","incur","inept","inert","infer","infra","inlet",
        "input","inset","inter","ionic","irene","irony","itchy","ivory",
        // J
        "jaded","jazzy","jelly","jenna","jenny","jerky","jerry","jetty","jewel","jihad",
        "joker","jolly","josie","juice","juicy","julio","jumbo","junta","juror",
        // K
        "kappa","karma","kayak","kebab","kerry","keyed","khaki","kiosk","kitty","knack",
        "kneel","knelt","knock","knoll","koala","kodak","kraft","kudos",
        // L
        "laced","laden","lager","laird","laker","lance","lapse","largo","larry","larva",
        "laser","latch","latex","lathe","laura","lazar","leach","leafy","leaky","leapt",
        "lease","leash","ledge","leech","legit","lemon","lever","levin","liang","libel",
        "liber","libra","liege","lilac","limbo","lined","linen","liner","lingo","liter",
        "liver","livid","llama","lobby","locus","lodge","lofty","logic","login","lohan",
        "lolly","lorry","loser","lotto","lotus","lough","lousy","lover","lowly","loyal",
        "lucid","lumen","lumpy","lunar","lunge","lupus","lymph","lynch","lyric",
        // M
        "macao","macro","madam","madly","magma","maize","maker","malik","mamma","manga",
        "mango","mania","manic","manly","manna","manny","manor","manta","manus","maple",
        "marco","marge","maria","marsh","mason","masse","mater","matte","mavis","maxim",
        "meaty","medal","medic","melee","melon","merch","mercy","merge","merit","merle",
        "merry","messy","meter","micro","midst","milky","mille","mimic","mince","miner",
        "minus","mirza","missy","misty","mixer","mocha","modal","moist","molar","molly",
        "mommy","monte","moody","moose","moray","morph","morse","motel","motif","motto",
        "mould","mound","mourn","mouse","mover","mower","mucus","muddy","mufti","mulch",
        "mummy","munch","mural","murky","mushy","musty","myron",
        // N
        "nadir","naive","nancy","nanny","nasal","nasty","natal","naval","navel","neath",
        "needy","nerve","nexus","niche","nicky","niece","nifty","ninth","nitro","noble",
        "noisy","nomad","noose","norma","nosed","notch","nudge","nutty","nylon","nymph",
        // O
        "oasis","obese","oddly","oiled","olden","olive","omega","onion","onset","opera",
        "optic","orbit","ortho","otter","ought","ounce","outed","outer","overt","owing",
        "oxide","ozone",
        // P
        "pablo","paced","padre","pagan","paler","palma","palsy","panda","panic","paolo",
        "papal","parma","parry","parse","pasha","paste","patch","patel","patio","patty",
        "pause","payed","payer","peach","pearl","pecan","pedal","pedro","peeve","peggy",
        "penal","pence","penny","perch","peres","peril","perky","perry","pesky","petal",
        "petit","petty","phony","piano","picky","piety","piggy","pilar","piled","pinch",
        "pinky","pinto","pious","piped","piper","pique","pivot","pixie","plaid","plank",
        "playa","plaza","plead","pluck","plumb","plume","plump","plush","poise","poked",
        "poker","polar","polio","polka","ponce","pooch","poppy","porch","porta","porto",
        "posey","posse","pouch","pound","prank","prawn","prima","prism","prius","privy",
        "probe","prone","prong","prose","proto","proxy","prune","psalm","psych","puffy",
        "pulse","punch","punta","pupil","puppy","purdy","puree","purge","purse","putty",
        // Q
        "quack","quail","quake","quark","quart","quasi","quell","query","quest","queue",
        "quill","quilt","quirk","quota",
        // R
        "rabbi","rabid","racer","radar","radon","rainy","rally","ralph","ranch","randy",
        "rapid","rated","ratio","raven","rayon","razer","razor","react","realm","rebel",
        "recap","recon","reddy","reese","reeve","regal","reign","reina","relax","relay",
        "relic","remit","remix","renal","renew","repay","repel","rerun","reset","resin",
        "reuse","revel","rhine","rhino","rhyme","rider","ridge","rifle","rigid","rigor",
        "riley","rinse","risen","riser","risky","rival","roach","roast","robin","robot",
        "rocky","rodeo","rogan","roger","rogue","rohan","rondo","roost","roper","rotor",
        "rouge","rouse","rover","rowan","rowdy","rower","ruddy","rufus","ruler","rumor",
        "runny","rupee","rusty","ryder",
        // S
        "saber","sable","sadly","sahib","salad","salle","sally","salon","salty","salve",
        "salvo","samba","sammy","sandy","sassy","satan","satin","sauce","saucy","sauna",
        "saver","savor","savoy","savvy","sawed","scala","scalp","scaly","scant","scare",
        "scarf","scary","scent","scion","scold","scoop","scope","scorn","scour","scout",
        "scrap","scrub","scrum","sedan","seedy","seine","seize","senna","serge","serra",
        "serum","servo","seton","setup","sever","sewed","sewer","shack","shade","shady",
        "shaft","shake","shaky","shale","shalt","shank","shard","shark","shave","shawl",
        "shear","sheen","sheep","sheer","sheik","shelf","shell","sheng","shine","shiny",
        "shire","shoal","shone","shook","shore","shout","shove","shred","shrub","shrug",
        "shunt","sided","siege","sieve","sigma","silky","silly","silva","singh","sinus",
        "siren","sixth","sixty","sized","skate","skier","skies","skirt","skull","skunk",
        "slack","slade","slain","slang","slant","slash","slate","sleek","sleet","slept",
        "slice","slick","slide","slime","slimy","sling","sloan","sloop","sloth","slump",
        "slung","slush","smack","smash","smear","smelt","smirk","smite","smoky","smyth",
        "snack","snail","snake","snape","snare","sneak","snell","sniff","snipe","snoop",
        "snort","snout","snowy","snuck","sober","soggy","sonar","sonic","sonny","spade",
        "spank","spare","spark","spasm","spawn","spear","speck","spell","spelt","spice",
        "spicy","spied","spike","spill","spilt","spine","spire","spite","spoil","spoof",
        "spook","spool","spoon","spore","spout","spray","spree","spurt","squat","squid",
        "stack","stain","stair","stake","stale","stalk","stall","stamp","stare","stark",
        "stash","stave","stead","steak","steed","steep","steer","stein","stent","stern",
        "stiff","sting","stink","stint","stoic","stoke","stole","stomp","stony","stool",
        "stoop","stork","stout","stove","strap","straw","stray","strut","stump","stung",
        "stunt","suave","suede","suing","suite","sully","sunny","surat","surge","surly",
        "sutra","swain","swami","swamp","swarm","swath","sweat","sweep","swell","swept",
        "swift","swine","swing","swipe","swirl","swish","swiss","swoon","swoop","sword",
        "swore","sworn","swung","synod","syrup",
        // T
        "taboo","tacit","tacky","taint","taker","takin","tally","talon","tammy","tango",
        "tania","taper","tarot","tasty","taunt","taxed","teary","tease","teeny","tempo",
        "tempt","tenet","tenor","tense","tenth","terry","thane","theft","theta","thief",
        "thigh","thine","thong","thorn","thumb","thump","thyme","tiara","tibet","tibia",
        "tidal","tiger","tiled","tilly","timed","timer","timid","timor","tinge","tipsy",
        "tithe","toast","token","tommy","tonal","toned","toner","tonga","tonic","tooth",
        "topaz","torah","torch","torso","totem","towel","toxic","toxin","trace","tract",
        "trait","tread","triad","tribe","trier","trite","troll","troop","trope","trout",
        "trove","truce","truer","trunk","truss","tulip","tummy","tumor","tuned","tuner",
        "tunic","turbo","tutor","twain","tweak","tweed","tween","tweet","twine","twink",
        "twist","tying",
        // U
        "ulcer","ultra","uncut","undue","unfit","unify","unite","unity","usage","usher",
        "utter",
        // V
        "vague","valet","valid","valor","valve","vapor","vault","venom","venue","verge",
        "verse","verve","vexed","vicar","vigil","vigor","villa","ville","vinny","vinyl",
        "viola","viper","viral","visor","vista","vital","vivid","vocal","vogue","voter",
        "vouch","vowed","vowel","vying",
        // W
        "wacky","wafer","waged","wager","wagon","waist","waive","wally","walsh","waltz",
        "waned","wasnt","waugh","waved","weary","weave","weber","wedge","weigh","welsh",
        "whack","whale","wharf","wheat","whiff","whine","whiny","whirl","whisk","whoop",
        "widen","widow","width","wield","wigan","wight","winch","windy","wiper","wired",
        "wiser","witch","witty","wonky","wound","woven","wrath","wreak","wreck","wrist",
        // X
        "xenon",
        // Y
        "yacht","yahoo","yearn","yeast","yield","youve","yummy",
        // Z
        "zebra","zoned",
    ]
